### PR TITLE
Create sv-SE.php

### PR DESCRIPTION
**Pull request by jms-du-se**
Here is a Swedish language file.
My collegues will review the translations, so there might be another update later on. :)

### CODE REVIEW

**Comment by ghost** [comment]
Thanks!

**Comment by jms-du-se** [comment]
Geen probleem! Altijd leuk om te helpen. 😊

//Jasper

Från: François Kooman ***@***.***>
Skickat: den 27 april 2022 13:15
Till: eduvpn/vpn-user-portal ***@***.***>
Kopia: Jasper Metselaar (HDa) ***@***.***>; Author ***@***.***>
Ämne: Re: [eduvpn/vpn-user-portal] Create sv-SE.php (PR #192)

You don't often get email from ***@***.******@***.***>. Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Thanks!

**Comment by ghost** [comment]
One more question:

```
        return [
            'en-US' => 'English',
            'ar-MA' => 'العربية',
            'da-DK' => 'Dansk',
            'de-DE' => 'Deutsch',
            'es-LA' => 'español',
            'et-EE' => 'Eesti',
            'fr-FR' => 'Français',
            'nb-NO' => 'norsk bokmål',
            'nl-NL' => 'Nederlands',
            'pl-PL' => 'polski',
            'pt-PT' => 'Português',
            'ro-RO' => 'română',
            'uk-UA' => 'Українська',
        ];
```

What is the 'native' translation of "Swedish"? Is it "Svensk" or "Svenska"?

**Comment by jms-du-se** [comment]
Hi François,

It should be “svenska”  (with a lowercase s).

//Jasper



Från: François Kooman ***@***.***>
Skickat: den 27 april 2022 13:21
Till: eduvpn/vpn-user-portal ***@***.***>
Kopia: Jasper Metselaar (HDa) ***@***.***>; Author ***@***.***>
Ämne: Re: [eduvpn/vpn-user-portal] Create sv-SE.php (PR #192)


One more question:

        return [



            'en-US' => 'English',



            'ar-MA' => 'العربية',



            'da-DK' => 'Dansk',



            'de-DE' => 'Deutsch',



            'es-LA' => 'español',



            'et-EE' => 'Eesti',



            'fr-FR' => 'Français',



            'nb-NO' => 'norsk bokmål',



            'nl-NL' => 'Nederlands',



            'pl-PL' => 'polski',



            'pt-PT' => 'Português',



            'ro-RO' => 'română',



            'uk-UA' => 'Українська',



        ];



What is the 'native' translation is "Swedish"? Is it "Svensk" or "Svenska"?

**Comment by ghost** [comment]
Done! https://github.com/eduvpn/vpn-user-portal/commit/58e4b588fb64591346ddb53e83578001ee877d37

Bedankt! :-)

**Pull request merged**
