### PR TITLE
implementing OpenIdAUthModule using mod_auth_openidc 

### PR DESCRIPTION
**Pull request by samermassoud**
the module has been tested with keycloak but should work with any openid provider.
documentation will be prepared for the auth module

### CODE REVIEW

**Comment by ghost** [comment]
Thanks for your contribution!

Some questions/remarks:
- `cookieName` as specified in the configuration template is not used anywhere, it would also violate the separation of concerns, we don't really want the VPN portal to manipulate 'external' cookies;
- `redirectURI` could probably be removed through "configuration by convention", i.e. require the endpoint to be always the same, which is to say, the default or recommended endpoint, just like it is [done](https://github.com/eduvpn/vpn-user-portal/blob/53486be30266ec276d2f7d7dd4d1580a8aa98589/src/Http/Auth/ShibAuthModule.php#L47) in e.g. the Shibboleth module;
- It seems `REMOTE_USER` is the default that should probably be used instead of the `HTTP_OPENID_SUB` header.

What do you think?

**Comment by samermassoud** [comment]
- `cookieName` was removed in followin commit. it is no longer required.
- `redirectURI` how about change it to $request->getRootUri()."/openid" , it will have to be then fixed in auth_openidc.conf as `https://vpn.example.org/vpn-user-portal/openid` .
- `REMOTE_USER` is the default, i included `HTTP_OPENID_SUB` to illustrate how to configure other options like using email that would be `HTTP_OPENID_EMAIL` .

let me know i can do the changes and commit  them, and also update the documentation before commit

**Comment by samermassoud** [comment]
the changes were applied 

- `cookieName` was removed
- `redirectURI` was removed. i.e. require the endpoint to be always the same, `https://vpn.example.org/vpn-user-portal/openid`
- `REMOTE_USER` is the default,

**Comment by ghost** [comment]
Excellent! Thanks! 

Would you be able to sign the CLA in order to contribute? See: https://github.com/eduvpn/vpn-user-portal/tree/v3#contributing

**Comment by samermassoud** [comment]
done and submitted back

**Comment by samermassoud** [comment]
> Excellent! Thanks!
> 
> Would you be able to sign the CLA in order to contribute? See: https://github.com/eduvpn/vpn-user-portal/tree/v3#contributing

**Comment by samermassoud** [comment]
closed by mistake
however i had some conflicts due to updates in config.php.example caused by updates following the pull request
conflict resolved and ready to merge

**Comment by ghost** [comment]
> done and submitted back

We haven't received it so far... Did you mail it to the two addresses mentioned in the README?

**Comment by samermassoud** [comment]
My bad,
Just forwarded the CLA to the 2 emails in the REAMME…


Regards,

Samer Massoud

**Comment by ghost** [comment]
Thanks!

**Comment by ghost** [comment]
We got the CLA, thanks!

https://github.com/eduvpn/vpn-user-portal/compare/v3...oidc

did some code style fixes, and will also review the documentation PR the figure out what this `HTTP_OPENID_ROLES` is, can't find it in the documentation anywhere...  It also looks unsafe in that the browser could probably provide this directly as a HTTP request header.

**Comment by ghost** [comment]
I've been experimenting with it, but running into some issue... for the permissions I'm trying to use `OIDC_CLAIM_eduperson_entitlement`, but it seems Apache (or PHP?) rewrites this to `REDIRECT_OIDC_CLAIM_eduperson_entitlement` which is weird. The `REMOTE_USER` works fine and is not modified in such a way. Do you have any idea what could cause this?

```
        'userIdAttribute' => 'REMOTE_USER',
        'permissionAttributeList' => ['OIDC_CLAIM_eduperson_entitlement'],
```

**Comment by samermassoud** [comment]
the initial prefix REDIRECT_ ot HTTP_ depends on the OIDCPassClaimsAs 
if you set as "headers", the cliams will have prefix HTTP_
if you set as "environment", the cliam will have prefix REDIRECT_
you can use "both" and you will have 2 sets of claims one starts with HTTP_ and the other with REDIRECT_

**Comment by ghost** [comment]
> the initial prefix REDIRECT_ ot HTTP_ depends on the OIDCPassClaimsAs if you set as "headers", the cliams will have prefix HTTP_ if you set as "environment", the cliam will have prefix REDIRECT_ you can use "both" and you will have 2 sets of claims one starts with HTTP_ and the other with REDIRECT_

Yes, I experimented with that, according to your documentation PR, but then the claim doesn't show up in the list, only the OIDC "standard" claims. It is all a bit confusing...

Edit: I try to understand/test everything myself so in case of trouble I can help people debug issues...

**Comment by samermassoud** [comment]
i want to make sure of onething, when setting OIDCClaimPrefix as in the documentation is  "openid-". 
if you used underscore "openid_" apache will not process the headers at all. when seting it as  "openid-" apache will convert hyphen to undersocre.
would you confirm if  OIDCClaimPrefix is set with undersocre of hyphen?

**Comment by ghost** [comment]
Thanks! Will look at it some more. Perhaps it is just the OP I'm using that does things differently...

**Comment by ghost** [comment]
The thing is *sometimes* it has the `REDIRECT_` prefix, but not always. Super weird.

Sometimes means: if I directly print `$_SERVER` in `index.php` it is without `REDIRECT_`, but if I don't print them and let the authentication mechanism take the `$_SERVER` variable it has the `REDIRECT_` prefix.  I have no clue what is going on.

Also, OIDC is even more difficult to debug than SAML :-)

**Comment by ghost** [comment]
Merged in v3 and part of 2.99.4 release. The permission stuff doesn't quite work for me yet, but the rest does. I did change the name of the classes and configuration fields (OpenId->Oidc) which is less confusing as we are talking about OpenID Connect and not OpenID :)

The `redirect_uri` is also different, now matches the suggestion from the mod_auth_openidc documentation.

**Comment by Moldisocks** [comment]
Just incase anyone else struggles immensely to get a 'roles' claim to work following the EduVPN OIDC documentation:

As @fkooman mentions above, you must use the prefix "REDIRECT_OIDC_CLAIM_{your claim name}" within the 'permissionAttributeList' array.

**Comment by Moldisocks** [comment]
The REDIRECT_OIDC_CLAIM_ prefix works when the user is accessing  /vpn-user-portal/ on any path other than /vpn-user/oauth/authorize.

/vpn-user-portal/oauth/authorize's request contains claims with OIDC_CLAIM_ prefix, without the REDIRECT. 

If your permissionAttributeList config is looking for REDIRECT_OIDC_CLAIM, you will notice that while some users can connect with eduVPN client OK, others are restricted access due to not having the correct permissions. 

Quick fix is to add both OIDC_CLAIM_{your claim} and REDIRECT_OIDC_CLAIM_{your claim} to permissionAttributeList in config.php

e.g
```php
'permissionAttributeList' => ['REDIRECT_OIDC_CLAIM_roles','OIDC_CLAIM_roles']
```

**Pull request merged**
