### PR TITLE
de_DE: Spelling fixes

### PR DESCRIPTION
**Pull request by bernhardschmidt**
Some spelling errors reported by our users

CLA is pending, should get to it soon

### CODE REVIEW

**Comment by ghost** [comment]
Thanks! You can also add yourself to the `locale/CREDITS.md` if you want.

**Comment by bernhardschmidt** [comment]
> Thanks! You can also add yourself to the `locale/CREDITS.md` if you want.

no thanks, really not necessary.

CLA has been signed.

**Comment by ghost** [comment]
Thanks! Will be part of the next release.

**Comment by ghost** [comment]
Part of 2.4.0 released today.

**Pull request merged**
