### PR TITLE
Changed and updated localisation file for Ukranian language uk_UA.php

### PR DESCRIPTION
**Pull request by Melkin1968**

### CODE REVIEW

**Comment by ghost** [comment]
Thanks!

**Comment by ghost** [comment]
One problem:

```
     'The list of applications you authorized to create a VPN connection.' => 'Список програм, яким ви надали дозвіл на створення VPN-з'єднання.',
```

There's a `'` in the translation. Is that supposed to be like this? Or is it a typo?

**Comment by ghost** [comment]
I guess it really is with `'`, з'єднання, so I escaped the `'` now.

**Comment by ghost** [comment]
https://github.com/eduvpn/vpn-user-portal/commit/f7e3ee168c8c46168f400458c0f38d34b3025501

**Comment by Melkin1968** [comment]
Yes, it really writes as з'єднання. So, please escape the ' symbol. Sorry for the inconvenience.
Thank you

**Pull request merged**
